"""
TypedDict defining the full state passed between nodes in the LangGraph
email-analysis pipeline.

`EmailAnalysisState` serves as the shared contract between all graph nodes.
Every node may read or write a subset of these fields while preserving
previous content (functional style). Fields are optional because different
nodes populate different parts of the state at different times.

This structure enables:
    • strong editor/type-checker support
    • predictable state evolution across the pipeline
    • clean decoupling between ML, heuristics, TI, LLMs, and SOC logic
"""

from typing import List, Literal, Optional, TypedDict, Dict, Any


# Categorical types for model clarity and strictness.
RiskLevel = Literal["low", "medium", "high"]
Decision = Literal["benign", "suspicious", "phishing"]


class EmailAnalysisState(TypedDict, total=False):
    """
    End-to-end state flowing through all analysis nodes.

    Fields are grouped by responsibility:
      • Input
      • Config
      • Classifier outputs
      • Heuristic/TI enrichment
      • Aggregated risk and high-level decision
      • LLM-generated explanations and safe replies
      • SOC and forensics sections
    """

    # --------------------
    # Raw input fields
    # --------------------
    subject: str            # Email subject string (may be empty)
    body: str               # Email body string (may be long)
    combined_text: str      # subject + "\n\n" + body, built by ingest_node

    # --------------------
    # Config / model selection
    # --------------------
    llm_model_name: str     # e.g. "qwen2.5:3b" — passed to LLMManager

    # --------------------
    # ML classifier outputs
    # --------------------
    p_benign: float         # Probability email is benign (from ML classifier)
    p_phishing: float       # Probability email is phishing (from ML classifier)

    # --------------------
    # Heuristic features and scoring
    # --------------------
    heuristic_score: float  # Score in [0,1] from rules/keyword/TLD extraction

    # --------------------
    # Threat intelligence data
    # --------------------
    urls: List[str]                         # URLs extracted from subject/body
    ti_results: List[Dict[str, Any]]        # Per-URL: flags from OpenPhish/URLHaus

    # --------------------
    # Aggregated risk and decision
    # --------------------
    risk_level: RiskLevel     # mapped from risk_score (low / medium / high)
    risk_score: float         # combined ML + heuristics + TI in [0,1]
    decision: Decision        # benign / suspicious / phishing

    # --------------------
    # LLM explainability + user-facing guidance
    # --------------------
    explanation: str          # Human-readable reasoning generated by LLM
    user_guidance: str        # Practical advice based on decision
    suggested_reply: str      # Safe email text drafted by LLM

    # --------------------
    # SOC / forensics
    # --------------------
    soc_recommendations: List[str]    # SOC operator workflow suggestions
    forensic_notes: str               # Compact summary for logging/dashboards
